---

stages:
  - test

molecule:
  stage: test
  image: $CI_REGISTRY/docker/molecule/alpine
  before_script:
    - git config --global
      url."$(expr match "$CI_REPOSITORY_URL" '\(.\+://[^/]*\)')/".insteadOf
      "git@$(expr match "$CI_REPOSITORY_URL" '.\+://.\+@\([^/]*\)'):"
  script:
    - molecule test
