---
- name: Enable KSM in kernel
  become: true
  template:
    src: etc/tmpfiles.d/ksm.conf.j2
    dest: /etc/tmpfiles.d/ksm.conf
    owner: root
    group: root
    mode: 0644
  notify: apply tmpfiles.d
  when:
    - netdata_ksm_enabled | bool

- name: Set variables for "netdata_config_*" variables
  include_tasks: loop_config_files.yml
  loop_control:
    loop_var: configfile
  loop: "{{ vars | select('match', 'netdata_config_') | map('extract', vars) | list }}"

- name: Disable telemetry (send anonymous statistic)
  become: true
  file:
    path: "{{ netdata_user_config_dir }}/.opt-out-from-anonymous-statistics"
    state: touch
    mode: 0644
    modification_time: preserve
    access_time: preserve
  when: netdata_telemetry | bool
