---

- name: Enable KSM in kernel
  template:
    src: etc/tmpfiles.d/ksm.conf.j2
    dest: /etc/tmpfiles.d/ksm.conf
    owner: root
    group: root
    mode: 0644
  notify: apply tmpfiles.d
  when:
    - netdata_ksm_enabled

- name: Set proper "netdata_config_ini_*" variables for inifiles
  include_tasks: loop_inifiles.yml
  loop_control:
    loop_var: inifile
  loop: "{{ vars | select('match', 'netdata_config_ini_') | map('extract', vars) | list }}"

- name: Set proper "netdata_config_yml_*" variables for yaml files
  include_tasks: loop_ymlfiles.yml
  loop_control:
    loop_var: ymlfile
  loop: "{{ vars | select('match', 'netdata_config_yml_') | map('extract', vars) | list }}"
