- name: "Set proper ini variables for section: {{ section }}"
  ini_file:
    path: "{{ netdata_user_config_dir }}/{{ inifile['path'] }}"
    section: "{{ section }}"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    mode: 0600
    owner: "{{ inifile.owner | default('netdata') }}"
    group: "{{ inifile.group | default('netdata') }}"
    no_extra_spaces: "{{ inifile.no_extra_spaces | default(False) }}"
  loop: "{{ inifile['data'][section] | dict2items }}"
  notify: restart netdata
