---

- name: "Include {{ netdata_installation_type }} tasks"
  include: "install_{{ netdata_installation_type }}.yml"

- name: Install required packages
  become: true
  yum:
    name: "{{ netdata_required_packages | union(netdata_required_packages_extra) | flatten }}"
    state: present

- name: Install netdata packages
  become: true
  yum:
    name: "{{ netdata_packages | union(netdata_packages_extra) | flatten }}"
    state: present
