---

- name: Download and install netdata
  block:
    - name: create temporary file
      tempfile:
        state: file
        suffix: temp
      register: netdata_tmp

    - name: Download netdata with check (sha256)
      get_url:
        url: "{{ netdata_tarball_url }}"
        dest: "{{ netdata_tmp.path }}"
        checksum: "{{ netdata_tarball_checksum }}"

    - name: Installing netdata
      shell: sh "{{ netdata_tmp.path }}" --accept -- --dont-start-it

  always:
    - name: Remove temporary netdata file
      file:
        path: "{{ netdata_tmp.path }}"
        state: absent

# TODO: install required packages
#- name: install required packages
#  yum:
#    state: present
#    name:
#      - python-dnspython
#      - python-ipaddress  # when isc-dhcpd installed and enabled
#      - python-mysqldb  # when mariadb or mysql installed and enabled
#      - python-psycopg2  # when postgres installed and enabled
#      - python-ldap  # when openldap is installed and enabled
# TODO: configs here
# /opt/netdata/var/log/netdata/error.log
# /opt/netdata/etc/netdata/stream.conf
#
# alarms default handler
#  '/opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.sh',
#   alarms default recipient 'root'
