---

- name: Check that the netdata executable exists
  become: true
  stat:
    path: /opt/netdata/INSTALLED.VERSION
  register: netdata_installed_version

- name: Read /opt/netdata/INSTALLED.VERSION file
  slurp:
    src: /opt/netdata/INSTALLED.VERSION
  register: netdata_installed_version_string
  when: netdata_installed_version.stat.exists

- name: Download and install netdata
  become: true
  block:
    - name: create temporary file
      tempfile:
        state: file
        suffix: temp
      register: netdata_tmp

    - name: Download netdata with check (sha256)
      get_url:
        url: "{{ netdata_tarball_url }}"
        dest: "{{ netdata_tmp.path }}"
        checksum: "{{ netdata_tarball_checksum }}"

    - name: Installing netdata
      command: sh "{{ netdata_tmp.path }}" --accept -- --dont-start-it

    - name: Save /opt/netdata/INSTALLED.VERSION file
      copy:
        content: "{{ netdata_tarball_release }}"
        dest: /opt/netdata/INSTALLED.VERSION

  always:
    - name: Remove temporary netdata file
      file:
        path: "{{ netdata_tmp.path }}"
        state: absent
  when: not netdata_installed_version.stat.exists
        or ((netdata_installed_version_string.content | default('') | b64decode) != netdata_tarball_release)
