---
- name: "Check that the user {{ inifile.path }} exists"
  stat:
    path: "{{ netdata_user_config_dir }}/{{ inifile.path }}"
    get_mime: false
    get_checksum: false
    get_attributes: false
  register: user_inifile_stat

- name: "Check that the stock {{ inifile.path }} exists"
  stat:
    path: "{{ netdata_stock_config_dir }}/{{ inifile.path }}"
    get_mime: false
    get_checksum: false
    get_attributes: false
  register: stock_inifile_stat

- name: Ensure netdata user config directory is exists
  file:
    path: "{{ netdata_user_config_dir }}/{{ inifile.path | dirname }}"
    state: directory
    mode: 0755

- name: "Copy the {{ inifile.path }} file if it doesn't exist already"
  copy:
    src: "{{ netdata_stock_config_dir }}/{{ inifile.path }}"
    dest: "{{ netdata_user_config_dir }}/{{ inifile.path }}"
    remote_src: true
  when: not user_inifile_stat.stat.exists and stock_inifile_stat.stat.exists

# Workaround with ansible nested variables
- name: "Render ansible variables for ini {{ inifile['path'] | basename }}"
  set_fact:
    rendered_inifile_data: "{{ lookup('template', 'render_inifile_data.j2') }}"

- name: "Set ini variables in {{ inifile.path }}"
  include_tasks: inifile.yml
  loop_control:
    loop_var: section
  loop: "{{ rendered_inifile_data.keys() | list }}"
