---
- name: "Check that the user {{ ymlfile.path }} exists"
  stat:
    path: "{{ netdata_user_config_dir }}/{{ ymlfile.path }}"
    get_mime: false
    get_checksum: false
    get_attributes: false
  register: user_ymlfile_stat

- name: "Check that the stock {{ ymlfile.path }} exists"
  stat:
    path: "{{ netdata_stock_config_dir }}/{{ ymlfile.path }}"
    get_mime: false
    get_checksum: false
    get_attributes: false
  register: stock_ymlfile_stat

- name: Ensure netdata user config directory is exists
  file:
    path: "{{ netdata_user_config_dir }}/{{ ymlfile.path | dirname }}"
    state: directory
    mode: 0755

- name: "Copy the stock {{ ymlfile.path }} file if it doesn't exist already"
  copy:
    src: "{{ netdata_stock_config_dir }}/{{ ymlfile.path }}"
    dest: "{{ netdata_user_config_dir }}/{{ ymlfile.path }}"
    remote_src: true
  when: not user_ymlfile_stat.stat.exists and stock_ymlfile_stat.stat.exists

- name: "Read yaml file {{ ymlfile.path }}"
  slurp:
    src: "{{ netdata_user_config_dir }}/{{ ymlfile.path }}"
  register: yml_file_data
  when: stock_ymlfile_stat.stat.exists

- name: "Set yaml data to file {{ ymlfile.path }}"
  copy:
    dest: "{{ netdata_user_config_dir }}/{{ ymlfile.path }}"
    content: "{{ yml_data | default({}, true) | combine(ymlfile.data, recursive=True) | to_nice_yaml }}"
  vars:
    yml_data: "{{ yml_file_data.content | default('') | b64decode | from_yaml }}"
