---
- name: Include config tasks
  ansible.builtin.include_tasks: config.yml
  tags:
    - configure

- name: "Include {{ netdata_installation_type }} tasks"
  ansible.builtin.include_tasks: "install_{{ netdata_installation_type }}.yml"
  tags:
    - install

- name: Ensure netdata service is started and enabled at boot
  become: true
  ansible.builtin.service:
    name: netdata
    state: started
    enabled: true
  tags:
    - configure
    - install
  when:
    - netdata_installation_type in ['package', 'tarball']
