---
# Workaround with ansible nested variables
- name: Render ansible variables for ini {{ configfile.path | basename }}
  set_fact:
    rendered_inifile_data: "{{ lookup('template', 'render_inifile_data.j2') }}"

- name: Set ini variables in {{ configfile.path }}
  include_tasks: inifile.yml
  loop_control:
    loop_var: section
  loop: "{{ rendered_inifile_data.keys() | list }}"
