---

netdata_required_packages: []

netdata_packages:
  - iproute
  - nmap-ncat
  - lm_sensors
  - python3
  - python3-dns

netdata_docker_required_packages: []

netdata_docker_packages:
  - python3  # For venv
  - "{{ 'python{v}-setuptools'.format(v={2: '', 3: '3'}[ansible_python.version.major]) }}"
