---

- name: Restart netdata handler
  become: true
  ansible.builtin.service:
    name: netdata
    state: restarted
  listen:
    - restart netdata package
    - restart netdata tarball

- name: Restart netdata docker
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  changed_when: false
  ansible.builtin.shell: |-
    test -f "{{ netdata_docker_venv_dir }}/bin/activate" \
      && . "{{ netdata_docker_venv_dir }}/bin/activate"
    docker-compose restart {{ netdata_docker_service_name }}
  args:
    chdir: "{{ netdata_docker_dir }}"
  listen:
    - restart netdata docker

- name: Apply tmpfiles.d
  become: true
  changed_when: false
  ansible.builtin.command: systemd-tmpfiles --create
  when: not ansible_virtualization_type in ['docker', 'lxc', 'systemd-nspawn']
