---

- name: restart netdata
  become: yes
  systemd:
    name: netdata
    state: restarted

- name: apply tmpfiles.d
  become: yes
  command: systemd-tmpfiles --create
  when: not ansible_virtualization_type in ['docker', 'lxc', 'systemd-nspawn']
