---
platforms:
  - &platform-basic
    name: molecule-netdata-package-el7-${CI_JOB_ID:-1}
    image: centos:7
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var
    tmpfs:
      - /tmp
      - /run
    keep_volumes: false
    tty: true  # For show system logs in docker logs
    command: /lib/systemd/systemd
    stop_signal: SIGRTMIN+3
    privileged: true
    security_opts:
      - apparmor=unconfined
      - seccomp=unconfined
    capabilities:
      - SYS_ADMIN  # For systemd
      - NET_ADMIN  # For dockerd
      - SYS_RESOURCE  # For dockerd oom_score_adj
    groups:
      - netdata
      - netdata_package
  # Disabled because netdata package not supplied for el9
  # - <<: *platform-basic
  #   name: molecule-netdata-package-el9-${CI_JOB_ID:-1}
  #   image: quay.io/centos/centos:stream9
  #   groups:
  #     - netdata
  #     - netdata_package
  - <<: *platform-basic
    name: molecule-netdata-tarball-el7-${CI_JOB_ID:-1}
    image: centos:7
    groups:
      - netdata
      - netdata_tarball
  - <<: *platform-basic
    name: molecule-netdata-tarball-el9-${CI_JOB_ID:-1}
    image: quay.io/centos/centos:stream9
    groups:
      - netdata
      - netdata_tarball
  - <<: *platform-basic
    name: molecule-netdata-docker-el7-${CI_JOB_ID:-1}
    image: centos:7
    privileged: true  # For docker
    groups:
      - netdata
      - docker
      - netdata_docker
  - <<: *platform-basic
    name: molecule-netdata-docker-el9-${CI_JOB_ID:-1}
    image: quay.io/centos/centos:stream9
    privileged: true  # For docker
    groups:
      - netdata
      - docker
      - netdata_docker
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      stdout_callback: debug
      error_on_undefined_vars: true
      callback_whitelist: profile_tasks
    diff:
      always: true
verifier:
  name: ansible
driver:
  name: docker
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint --force-color -p .
