---
platforms:
  - &platform-basic
    name: molecule-netdata-package-el7-${CI_JOB_ID:-1}
    image: centos:7
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    stop_signal: SIGRTMIN+3
    privileged: false
    capabilities:
      - SYS_ADMIN  # For systemd
    groups:
      - netdata
      - netdata_package
  - <<: *platform-basic
    name: molecule-netdata-package-el8-${CI_JOB_ID:-1}
    image: centos:8
    groups:
      - netdata
      - netdata_package
  - <<: *platform-basic
    name: molecule-netdata-tarball-el7-${CI_JOB_ID:-1}
    image: centos:7
    groups:
      - netdata
      - netdata_tarball
  - <<: *platform-basic
    name: molecule-netdata-tarball-el8-${CI_JOB_ID:-1}
    image: centos:8
    groups:
      - netdata
      - netdata_tarball
  - <<: *platform-basic
    name: molecule-netdata-docker-el7-${CI_JOB_ID:-1}
    image: centos:7
    privileged: true  # For docker
    groups:
      - netdata
      - docker
      - netdata_docker
  - <<: *platform-basic
    name: molecule-netdata-docker-el8-${CI_JOB_ID:-1}
    image: centos:8
    privileged: true  # For docker
    groups:
      - netdata
      - docker
      - netdata_docker
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      stdout_callback: debug
      error_on_undefined_vars: true
      callback_whitelist: profile_tasks
    diff:
      always: true
verifier:
  name: ansible
driver:
  name: docker
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint --force-color -p .
