---

platforms:
  - name: molecule-netdata-el7-${CI_JOB_ID:-1}
    image: centos:7
    pull: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /usr/sbin/init
    stop_signal: "SIGRTMIN+3"
    privileged: true
    capabilities:
      - SYS_ADMIN  # For systemd
  # - name: molecule-netdata-el8-${CI_JOB_ID:-1}
  #   image: centos:8
  #   pull: true
  #   volumes:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  #   command: /usr/sbin/init
  #   stop_signal: "SIGRTMIN+3"
  #   privileged: true
  #   capabilities:
  #     - SYS_ADMIN  # For systemd
provisioner:
  name: ansible
  log: true
  options:
    vvv: false
  config_options:
    defaults:
      stdout_callback: debug
      error_on_undefined_vars: true
      callback_whitelist: profile_tasks
    diff:
      always: true
  lint:
    name: ansible-lint
    options:
      force-color: true
verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    verbose: true
driver:
  name: docker
lint:
  name: yamllint
dependency:
  name: galaxy
