---
platforms:
  - &platform-basic
    name: molecule-netdata-package-fc37-${CI_JOB_ID:-1}
    image: fedora:37
    command: /lib/systemd/systemd
    stop_signal: SIGRTMIN+3
    tty: true  # For journald and capture stdout/sdterr via docker
    tmpfs:
      - /run
    keep_volumes: false
    volumes:
      - /lib/docker
      - /lib/modules:/lib/modules:ro
    privileged: true  # For dockerd
    capabilities:
      - SYS_ADMIN  # For systemd
      - NET_ADMIN  # For dockerd
      - SYS_MODULE  # For dockerd and modprobe
      - SYS_RESOURCE  # For dockerd oom_score_adj
    security_opts:
      - apparmor=unconfined
      - seccomp=unconfined
    groups:
      - netdata
      - netdata_package
  - <<: *platform-basic
    name: molecule-netdata-tarball-fc37-${CI_JOB_ID:-1}
    groups:
      - netdata
      - netdata_tarball
  - <<: *platform-basic
    name: molecule-netdata-docker-fc37-${CI_JOB_ID:-1}
    groups:
      - netdata
      - docker
      - netdata_docker

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      stdout_callback: debug
      error_on_undefined_vars: true
      callbacks_enabled: profile_roles,profile_tasks,timer
      collections_paths: ./collections
      roles_paths: ./roles
    diff:
      always: true

verifier:
  name: ansible

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint --force-color .
