---

platforms:
  - name: molecule-netdata-el7-${CI_JOB_ID:-1}
    image: centos:7
    pull: false
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
    stop_signal: "SIGRTMIN+3"
    privileged: false
    capabilities:
      - SYS_ADMIN  # For systemd
  - name: molecule-netdata-el8-${CI_JOB_ID:-1}
    image: centos:8
    pull: false
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
    stop_signal: "SIGRTMIN+3"
    privileged: false
    capabilities:
      - SYS_ADMIN  # For systemd
provisioner:
  name: ansible
  inventory:
    host_vars:
      molecule-netdata-el8-${CI_JOB_ID:-1}:
        ansible_python_interpreter: /usr/bin/python3
  log: true
  config_options:
    defaults:
      stdout_callback: debug
      error_on_undefined_vars: true
      callback_whitelist: profile_tasks
    diff:
      always: true
verifier:
  name: testinfra
  options:
    verbose: true
driver:
  name: docker
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint --force-color
  flake8
