---

- name: Verify netdata is healthy
  register: _netdata_uri
  until: _netdata_uri is succeeded
  retries: 15
  delay: 1
  ansible.builtin.uri:
    url: http://127.0.0.1:19999/
    method: GET
    validate_certs: false
    use_proxy: false
    status_code:
      - 200

- name: Include tasks for {{ netdata_installation_type }}
  ansible.builtin.include_tasks: "{{ netdata_installation_type }}.yml"
